FROM wordpress:latest

RUN apt-get update \
    && apt-get install -y libxml2-dev \
    && docker-php-ext-install dom

RUN pecl install "xdebug" \
    && docker-php-ext-enable xdebug

RUN echo "xdebug.mode=debug" >> /usr/local/etc/php/conf.d/xdebug.ini && \
    echo "xdebug.start_with_request=yes" >> /usr/local/etc/php/conf.d/xdebug.ini

RUN apt-get install -y npm

RUN npm install less -g \
    && npm install less-plugin-clean-css -g


#COMPOSER 
RUN curl -sS https://getcomposer.org/installer | php \
&& mv composer.phar /usr/local/bin/composer

#PHPUNIT
RUN composer global require "phpunit/phpunit"

ENV PATH /root/.config/composer/vendor/bin:$PATH

RUN ln -s /root/.config/composer/vendor/bin/phpunit /usr/bin/phpunit

#install wp cli
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
RUN chmod +x /usr/local/bin/wp
